version: '3'
services:
  reverse-proxy:
    image: traefik
    command: --api.insecure=true --providers.docker --providers.docker.exposedByDefault=false
    restart: "no"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  microservice-rgbtohex:
    build: rgb\rgb-hex
    restart: "no"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.microservice-rgbtohex.rule=PathPrefix(`/rgbtohex`)"
      - "traefik.http.routers.microservice-rgbtohex.middlewares=microservice-rgbtohex-stripprefix"
      - "traefik.http.services.microservice-rgbtohex.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.microservice-rgbtohex-stripprefix.stripprefix.prefixes=/rgbtohex"

  microservice-hsltohex: 
    build: hsl\hsl-hex
    restart: "no"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.microservice-hsltohex.rule=PathPrefix(`/hsltohex`)"
      - "traefik.http.routers.microservice-hsltohex.middlewares=microservice-hsltohex-stripprefix"
      - "traefik.http.services.microservice-hsltohex.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.microservice-hsltohex-stripprefix.stripprefix.prefixes=/hsltohex"

#  <microservice-example-name>:
#    build: <microservice-example-name>
#    restart: "no"
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.<microservice-example-name>.rule=PathPrefix(`/<microservice-example-name>`)"
#      - "traefik.http.routers.<microservice-example-name>.middlewares=<microservice-example-name>-stripprefix"
#      - "traefik.http.services.<microservice-example-name>.loadbalancer.server.port=3000"
#      - "traefik.http.middlewares.<microservice-example-name>-stripprefix.stripprefix.prefixes=/<microservice-example-name>"
